const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  ITEM_UPDATE_START: 'ITEM_UPDATE_START',
  ITEM_UPDATE_SUCCESS: 'ITEM_UPDATE_SUCCESS',
  ITEM_UPDATE_FAILURE: 'ITEM_UPDATE_FAILURE'
};

export default ShopActionTypes;
